// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// salso_Rcpp_unsafe
Rcpp::List salso_Rcpp_unsafe(const Rcpp::NumericMatrix& p, int maxClust, double Const_Binder, int nPerm, int nScans);
RcppExport SEXP _salsocustom_salso_Rcpp_unsafe(SEXP pSEXP, SEXP maxClustSEXP, SEXP Const_BinderSEXP, SEXP nPermSEXP, SEXP nScansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type maxClust(maxClustSEXP);
    Rcpp::traits::input_parameter< double >::type Const_Binder(Const_BinderSEXP);
    Rcpp::traits::input_parameter< int >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< int >::type nScans(nScansSEXP);
    rcpp_result_gen = Rcpp::wrap(salso_Rcpp_unsafe(p, maxClust, Const_Binder, nPerm, nScans));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_salsocustom_salso_Rcpp_unsafe", (DL_FUNC) &_salsocustom_salso_Rcpp_unsafe, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_salsocustom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
