# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.salso <- function(epam, maxClusts, Const_Binder, batchSize, nScans, maxThreads, timeLimit) {
    .Call(`_salsocustom_salsoRcpp`, epam, maxClusts, Const_Binder, batchSize, nScans, maxThreads, timeLimit)
}

