# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.salso <- function(p, maxClust, Const_Binder = 0.5, nPerm = 10000L, nScans = 3L) {
    .Call(`_salsocustom_salso_Rcpp_unsafe`, p, maxClust, Const_Binder, nPerm, nScans)
}

